
version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: nest-pokemons
    volumes:
      - /absolute/path/to/mongo-data:/data/db:rw

